# .github/workflows/sql-deploy.yml
on: 
  push:
  workflow_dispatch:

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: dotnet build ./DatabaseProjectWideWorldImporters.sqlproj
    
