# .github/workflows/sql-deploy.yml
on: 
  push:
  workflow_dispatch:

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - run: dotnet build /p:NetCoreBuild=true /p:OutputPath=./Output ./DatabaseProjectWideWorldImporters.sqlproj
    
    - uses: actions/upload-artifact@v3
      with:
          name: dacpac-artifact
          path: ./Output
    
