# .github/workflows/sql-deploy.yml
on: 
  push:
  workflow_dispatch:

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/sql-action@v1.3
      with:        
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        project-file: './Database.sqlproj'
        build-arguments: '-c Release'                 # Optional arguments passed to dotnet build
        arguments: '/p:DropObjectsNotInSource=true'   # Optional parameters for SqlPackage Publish
  DeployDev:
    runs-on: windows-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v1
    - uses: azure/sql-action@v1.3
      with:
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        dacpac-package: './Database.dacpac'
        arguments: '/p:DropObjectsNotInSource=true'   # Optional parameters for SqlPackage Publish
