# This is a basic workflow to help you get started with Actions

name: Report Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Report:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: azure-resource-login
        uses: Azure/azure-resource-login-action@v1.0.0
        id: sql-login
        with:
          # Azure credentials for the service principal to log in
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          # Canonical resource url for what you want the token for
          resource-url: "https://database.windows.net"
    
    
      - name: Identifying proposed changes
        uses: Azure/run-sqlpackage-action@v1.0.0
        with:
           action: 'DeployReport'
           sourcepath: build
           outputpath: reports
           outputfile: 'deployreport.xml'
           profile: DatabaseProjectTestDB.profile.xml
           authtoken: ${{ steps.sql-login.outputs.token }}
